name: analytics
description: Package for analytics and tracking features in the application.
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.7.2

dependencies:
 flutter:
    sdk: flutter
 collection: ^1.19.1
meta: any
collection: any
dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
