name: ignitor
description: A Flutter template that serves as a boilerplate for building scalable and maintainable apps. https://github.com/4uzhoy/ignitor
publish_to: 'none' 
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.3 <4.0.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
 #localization
  flutter_localizations:
    sdk: flutter
  localization:
    path: ../packages/localization
  intl: ^0.19.0

  #analytics
  analytics: 
    path: ../packages/analytics

  #utils
  tinygram: ^1.0.2
  pubspec_generator: ^4.0.0
  collection: any
  path: any
  meta: any
  uuid: any

  #ui
  ui:
   path: ../packages/ui
  cupertino_icons: ^1.0.8
  google_fonts: any
  font_awesome_flutter: ^10.7.0

  #clients
  client:
    path: ../packages/client
  json_annotation: ^4.9.0

  #storage
  kv_preferences: ^1.0.0

  #logger
  l: ^5.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.4.0
  flutter_gen: ^5.4.0
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons: #dart run flutter_launcher_icons
  ios: true
  android: true
  image_path: ""
  remove_alpha_ios: true
  min_sdk_android: 21  

flutter:
  uses-material-design: true

flutter_gen:
  output: lib/src/common/constant/ # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    rive: true
    lottie: true
        
