version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: /
    target-branch: main
    reviewers:
      - 4uzhoy
    commit-message:
      prefix: chore