name: root
description: "Workspace root"

environment:
  sdk: ">=3.7.0 <4.0.0"
  flutter: ">=3.29.3 <4.0.0"

workspace:
  - application
  - packages/domain
  - packages/ui
  - packages/localization
  - packages/analytics
  - packages/client
