name: localization
description: Localization layer of the application, providing translations and locale management.
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ">=3.27.0"

dependencies:
 flutter:
    sdk: flutter
 flutter_localizations:
    sdk: flutter
 sheety_localization: ^0.1.3
 intl: 0.20.2


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
