name: ui
description: Package for themes, widgets, and UI components of the application.
version: 0.0.1

resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ">=3.27.0"

dependencies:
 flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
