name: CI

on:
  push:
    branches: [ "work" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install dependencies
        run: flutter pub get
      - name: Install pre-commit
        run: pip install pre-commit
      - name: Format
        run: pre-commit run --all-files
      - name: Analyze
        run: flutter analyze
      - name: Test
        run: dart test
